name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3.1'

    - name: Clean cache
      run: sudo rm -rf ~/Library/Caches/org.swift.swiftpm/

    - name: Install dependencies
      run: swift package resolve

    - name: Build
      run: swift build --enable-test-discovery -v

    - name: Run tests
      run: swift test --enable-test-discovery -v
